
const listComp = ["FUNDAS","GOMITAS","CINTA ADHESIVA","FLEJE",
"LABEL 4 X 6"
]

const listBathroom = ["PAPEL HIGIENICO","TOALLA PRECORTADA"
]

const listTypes = ["COMPONENTES","INSUMOS PARA BAÑOS",
"MATERIALES PARA OFICINA","HORNO","REACTIVO", "5000 S/S",
"5000B S/S", "5400 L/S", "260A", "260Y","MONITO","SUNSHINE S/S","SUNSHINE L/S",
"SUNSHINE A-SWEATSHIRT","SUNSHINE Y-SWEATSHIRT","SUNSHINE A-HOODIE","SUNSHINE Y-HOODIE","RUBEN S/S","RUBEN L/S",
"RUBEN A-SWEATSHIRT","RUBEN Y-SWEATSHIRT","RUBEN A-HOODIE","RUBEN Y-HOODIE", "RUBEN DRESS","RUBEN MONITO"
]

const listOffice = ["RESMA DE PAPEL 8 1/2 x 11"
]

const listHorno = [
"YL482 55G-FLO YELLOW","400 55G-FLO PINK","BERZAFLUOR PINK BB",
"BL563 55G FLO BLUE","BL6011 BLUE/R","R903-17 MINT GREEN","VL401 FLO VIOLET",
"N3790 TURQ/F","R731-15 55G/GREY","N3737 55G/ROYAL BLUE","BLACK 30 5G JET BLACK",
"BEZAFLUOR GREEN BT","GOLDEN YELLOW","R910-17 VIOLET BS","N3307 5G PINK 3B",
"BEZAFLUOR AMARILLO BA","BEZAPRINT BLACK DW","BEZAFLUOR BLUE BB","BEZAPRINT MARINO RRM",
"BEZAPRINT BLUE BT","CS CONC TUBILOCK","DENIMCOL BINDER GF-C","ASUPREND WS","FELOSAN",
"NA7227 WETTING AGENT","DENICOL WASH SD","PRECAT/REWIN","ULTRASCAUR LF-OS"
]

const listReactive = [
"SBF Bezativ Turquesa","S-8GN Bezativ Yellow","S3B Bezativ Red","SRL Bezativ Orange",
"VB Bezativ Black VB","Black Ultra DR","VRN Bezativ Blue","V-5R Bezativ Violet",
"S-3R Bezativ Yellow Gold","Soda Polska ciech","Sulfato de Sodio Sal","Sarabid MIP",
"Acido Aceitico Conc","Tubingal 2270","Soda Caustica"
]

const UM = ["KILO","GRAMO","COPA","UNIDAD","ROLLO","PAQUETE","LIBRA"]


export {
    listComp,
    listHorno,
    listReactive,
    UM,
    listTypes,
    listBathroom,
    listOffice
}